### ISSUE TITLE
mssqlclient new line/line wrapping

### ISSUE THREAD

**Issue by lewis20188** [fortra/impacket#1558] opened 2023-05-21 18:03 UTC
Hello, I'm currently having some issues getting mssqlclient to display its output correctly on Kali linux. It looks like there is some issue with line wrapping or processing the new line character. Not sure if this is some kind of bug or not, Thanks.

This is using parrot linux 6.1.15

![Selection_155](https://github.com/fortra/impacket/assets/73242574/3548338c-b107-4e50-abf4-1543bcfffa87)

This is using kali linux 5.18.16

![Selection_154](https://github.com/fortra/impacket/assets/73242574/375d3044-2f50-4fb8-be7d-af4efc4de86f)

**Comment by Sanmopre** [comment] 2023-06-30 13:24
I was not able to reproduce the same behavior in a Kali 5.18.0, could it be other environment variables like the console config?

**Comment by gabrielg5** [comment] 2023-09-12 22:41
No answer. Closing this one.
Reopen if necessary

**Closed by gabrielg5** 2023-09-12 22:41 UTC
Labels: waiting for response, medium
