### ISSUE TITLE
impacket-ntlmrelayx Error - AttributeError: 'int' object has no attribute 'getDialect'

### ISSUE THREAD

**Issue by abdelaziz-khaled** [fortra/impacket#1623] opened 2023-09-29 16:03 UTC
Hello,
I've got this error when i run this command on kali lunix:

sudo impacket-ntlmrelayx --no-http-server -smb2support -t 192.168.106.242 -c "powershell -nop -w hidden -e  My powershell code"

[*] Servers started, waiting for connections
[*] SMBD-Thread-4 (process_request_thread): Received connection from 192.168.220.242, attacking target smb://192.168.106.242
[-] SMBClient error: Connection was reset
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/impacket/smbserver.py", line 4439, in processRequest
    respCommands, respPackets, errorCode = self.__smb2Commands[smb2.SMB2_NEGOTIATE](
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/impacket/examples/ntlmrelayx/servers/smbrelayserver.py", line 158, in SmbNegotiate
    connData['EncryptionKey'] = client.getStandardSecurityChallenge()
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/impacket/examples/ntlmrelayx/clients/smbrelayclient.py", line 603, in getStandardSecurityChallenge
    if self.session.getDialect() == SMB_DIALECT:
       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/impacket/smbconnection.py", line 206, in getDialect
    return self._SMBConnection.getDialect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'int' object has no attribute 'getDialect'

Do you have any idea ?

**Comment by NodeRaven** [comment] 2023-10-04 18:30
I am also receiving this same exact error. Running Impack v.0.11.0.

**Comment by notatutaboi** [comment] 2023-10-09 06:48
Receiving the exact same error. I spoke to some of my friends and it seems like the problem is non-existing in v0.10. But facing a lot of issue downgrading to the sheer amount of dependencies, and ofc, python.

Any help would be appreciated.

**Comment by gabrielg5** [comment] 2023-10-15 23:12
Hi all,

I've been checking a bit this one, and your comment really helped @admslv, thanks!
I tested from a system with connectivity to the target and it worked ok; but when tried with a _non-existent_ target it failed as reported. Can you validate please @abdelaziz-khaled / @NodeRaven / @therealnota ?

I also tested in a v0.10 and result is the same (working fine in a reachable target and failing in a non-reachable one)

I'll analyze it a bit more to validate if can make more clear the error, instead of raising the raw exception as being done now

thank you!

**Comment by Habibdia** [comment] 2023-10-23 16:20
Hello,
I have this error too.
My target is avalaible, not proxy chains set.
Best regards,

**Comment by zsherminator** [comment] 2023-11-09 13:29
Hi, I'm having the same issue, running the same command as @abdelaziz-khaled 
The target is reachable yet the error occurs
![image](https://github.com/fortra/impacket/assets/70905313/95ecd357-c138-4127-ae3e-9f88b06f522c)

**Comment by NodeRaven** [comment] 2023-12-06 05:09
Still receiving this error...

**Comment by DonnieMarco** [comment] 2024-06-19 03:47
Just thought I would add my two cents. I am having the same issue running a similar command through Proxychains:
![Screenshot 2024-06-19 at 04 46 32](https://github.com/fortra/impacket/assets/63506913/96a601f0-de20-4038-9276-1c2b0c2876ea)

**Comment by DonnieMarco** [comment] 2024-06-19 03:58
Ok so I found my issue at least, it is because I was trying to relay to myself, I had a list of targets and one of them was the from the machine that I was executing the connection. Once I cut that IP address out this worked fine.

**Comment by sunsetorange1** [comment] 2024-09-10 00:51
Not sure if this helps anyone, but I was getting this error when using the "-t" flag against a .txt file.
When I noticed and changed it to "-tf" (for target file), it worked as expected.

Also make sure to remove any hosts with "SMB signing: true" from the target list.

**Comment by gabrielg5** [comment] 2024-10-10 23:26
Hey,

I've returned to this one... This error has been better handled in the context of https://github.com/fortra/impacket/commit/8856defa664f895b4d29d94c9715e535987411fc#diff-106052bd32fd67b0cf4c202ab82966b7ca33b4f0cb9caf50a0404bc0056c895fL870 (#1741)

https://github.com/fortra/impacket/blob/65b774ded17a79f1041397202852eab0c24cd039/impacket/examples/ntlmrelayx/servers/smbrelayserver.py#L882-L886

> Bugfix: initclient-> unhandled return status of client.initconnection, now properly raises an exception when that call fails

Can you please retry?
Thanks!

**Comment by gabrielg5** [comment] 2024-10-23 21:40
Closing this issue as already fixed. Please reopen if you face it again
Thank you!

**Closed by gabrielg5** 2024-10-23 21:40 UTC
Labels: bug, waiting for response, medium
