### ISSUE TITLE
SMB: Missing out of memory error handling 0x17000000

### ISSUE THREAD

**Issue by nikaiw** [fortra/impacket#1733] opened 2024-04-16 22:51 UTC
as describe in https://github.com/Pennyw0rth/NetExec/issues/258 , impacket/nt_errors.py seems to be missing the value 0x17000000 for handling what seems to be "out of memory" server error.

![image](https://github.com/fortra/impacket/assets/1255732/c3e13ab0-c929-4cee-8a70-98649cdd033e)

**Comment by anadrianmanrique** [comment] 2024-04-17 13:37
according to https://github.com/Pennyw0rth/NetExec/issues/258 ( altough it hasn't been specified ) I can infer impacket 0.11 it's being used in that scanrio. Changes related to NTSTATUS error handling were merged in order to handle unknown values at https://github.com/fortra/impacket/pull/1311. Please confirm wether the issue is still present in the master branch
Thanks

**Comment by mpgn** [comment] 2024-04-17 13:54
The PR you mention has been reverted https://github.com/fortra/impacket/pull/1714 so yes the issue is on master branch :)

**Comment by anadrianmanrique** [comment] 2024-04-17 16:30
Nope, changes were not reverted. https://github.com/fortra/impacket/blob/master/impacket/smb.py#L582 . In https://github.com/fortra/impacket/commit/0d2b72ae979bebaf8167a9bafa597fa1a0a6bfb5 we kept the older interface in order to avoid crashes in your code. Please recheck

**Closed** 2024-04-17 16:33 UTC
