### ISSUE TITLE
Impacket broke after updating Kali

### ISSUE THREAD

**Issue by init5-SF** [fortra/impacket#1484] opened 2023-02-15 19:41 UTC
### Issue
after running `apt update` and `apt full-upgrade` on Kali, all impacket scripts (psexec, wmiexec, etc.) broke and they show the same exact error below

### Configuration  
impacket version: v0.10.1.dev1+20230116.181610.efcaec35
Python version: 3.11.1
Target OS: Attacker: Linux kali 6.0.0-kali6-amd64

### Debug Output With Command String  
```
└─# psexec.py -h                                                                                  
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 617, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 956, in require
    needed = self.resolve(parse_requirements(requirements))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 815, in resolve
    dist = self._resolve_dist(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 861, in _resolve_dist
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (impacket 0.10.0 (/usr/lib/python3/dist-packages), Requirement.parse('impacket==0.10.1.dev1+20230116.181610.efcaec35'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/psexec.py", line 4, in <module>
    __import__('pkg_resources').run_script('impacket==0.10.1.dev1+20230116.181610.efcaec35', 'psexec.py')
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3248, in <module>
    @_call_aside
     ^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3223, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3261, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 619, in _build_master
    return cls._build_from_requirements(__requires__)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 632, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 815, in resolve
    dist = self._resolve_dist(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 856, in _resolve_dist
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'impacket==0.10.1.dev1+20230116.181610.efcaec35' distribution was not found and is required by the application
```

**Comment by reybango** [comment] 2023-02-26 01:13
@0xdeaddood I believe this is related to a Debian updated that made a change to Python. The Empire project had the same issue and just pushed an update to the setup script to allow installation of Empire 5.0. The CrackMapExec binary is also not working. I believe this change from Debian is affecting a lot of projects.

**Comment by init5-SF** [comment] 2023-02-28 22:34
@0xdeaddood hello,

I haven't tried re-installing, this is the impacket that comes preinstalled in Kali.
How do I get the version of `setuptools`?

**Comment by zAbuQasem** [comment] 2023-03-06 23:52
As @reybango mentioned earlier, the issue is related to latest Debian update which broke everything related to python3, even the work around they mentioned in the message that suggested using `pipx` needs more effort on kali to get it working.

**Comment by reybango** [comment] 2023-03-07 01:32
@zAbuQasem indeed. I ended up using the "--break-system-packages" switch which installed the scripts globally but I believe there has to be a better way to do this that doesn't break things. Maybe @0xdeaddood can give details of a workflow for using virtual environment install where you don't have to constantly turn on the virtual environment to make the scripts accessibly globally?

**Comment by ablito19** [comment] 2023-03-15 13:20
@reybango  What have you do exactly to make working ? do you remove impacket and install it again ?

**Comment by reybango** [comment] 2023-03-15 13:29
@ablito19 It depends on where you're installing it. I was installing on Kali and the Kali team just updated the OS with a patch to give people more time to get their python scripts fixed. So if you download the repo from here and install it, everything should work. I did that last night and all was fine for me. 

The patch is something the Kali team did so if you try to install Impacket on another Debian-based distro that's running Python 3.11, it may cause some breakage. I'm not sure as I've not tested it on other distros.

**Comment by ablito19** [comment] 2023-03-15 15:16
I'm on latest Kali and i use Repo from Github but i got same issus

**Comment by zAbuQasem** [comment] 2023-03-15 17:14
The only thing that worked for me was to apt mark hold python3 and  `sudo apt-mark hold linux-image-$(uname -r)`

**Comment by ablito19** [comment] 2023-03-16 15:52
Now, I got sqlite3.OperationalError : database is locked

**Comment by 0xdeaddood** [comment] 2023-03-17 03:24
> @0xdeaddood hello,
> 
> I haven't tried re-installing, this is the impacket that comes preinstalled in Kali. How do I get the version of `setuptools`?

Hi @init5-SF! It could be something related to issue described by @reybango. Please read this [comment](https://github.com/fortra/impacket/issues/1496#issuecomment-1473065740) and use the option that suits you best.

**Comment by 0xdeaddood** [comment] 2023-03-17 03:31
> As @reybango mentioned earlier, the issue is related to latest Debian update which broke everything related to python3, even the work around they mentioned in the message that suggested using `pipx` needs more effort on kali to get it working.

Hi @zAbuQasem!

I installed Impacket with `pipx` in Kali and everything worked fine. If the problem is related to the Impacket installation itself, please mentioned it [here](https://github.com/fortra/impacket/issues/1496).

**Comment by 0xdeaddood** [comment] 2023-03-30 13:38
Closing. Please re-open if needed.

**Closed by 0xdeaddood** 2023-03-30 13:38 UTC
Labels: waiting for response

**Comment by init5-SF** [comment] 2023-07-27 18:56
Hello,

How do I _safely_ uninstall the old broken impacket (the one that comes preinstalled in Kali) in order to install the latest version using pipx?

Thanks!
